### PR TITLE
Run delete-and-create if rebase fails

### PR DESCRIPTION
**Pull request by worgarside-dev**
- a89fa78 | Re-order release branch creator jobs
- d10b2dc | Run delete-and-create if rebase fails
- 16a79c8 | Fix condition
- 4619a0a | Fix IWhWs committing

### CODE REVIEW

**Review by worgarside — APPROVED** [review]

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/21

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/home-assistant-config-validator/pull/65
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/useful-devops-scripts/pull/191
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/28

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/home-assistant-config-validator/pull/65
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/30

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/home-assistant-config-validator/pull/65
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/30

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/home-assistant-config-validator/pull/65
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/81
- https://github.com/worgarside/addon-rss-log-feed/pull/74
- https://github.com/worgarside/addon-yas-209-bridge/pull/71
- https://github.com/worgarside/home-assistant-config-validator/pull/65
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/useful-devops-scripts/pull/192
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/32

**Pull request merged**
