### PR TITLE
Add README generator

### PR DESCRIPTION
**Pull request by worgarside-dev**
- 4dea225 | Add README generator
- 860f2df | Add as local PCH
- 92c6955 | More script improvements
- 87a039c | Add build stage for IWh
- 96382ff | Remove IWh publish GHA
- 891269e | Script updates

### CODE REVIEW

**Review by worgarside — APPROVED** [review]

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/79
- https://github.com/worgarside/addon-rss-log-feed/pull/72
- https://github.com/worgarside/addon-yas-209-bridge/pull/69
- https://github.com/worgarside/home-assistant/pull/421
- https://github.com/worgarside/home-assistant-config-validator/pull/63
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/useful-devops-scripts/pull/189
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/12
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/useful-devops-scripts/pull/190
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/12
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/17
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/17
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/addon-item-warehouse-website/pull/17
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/610

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse-api/pull/80
- https://github.com/worgarside/addon-rss-log-feed/pull/73
- https://github.com/worgarside/addon-yas-209-bridge/pull/70
- https://github.com/worgarside/home-assistant-config-validator/pull/64
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/610

**Pull request merged**
