### PR TITLE
Lint GHA sync workflows too

### PR DESCRIPTION
**Pull request by worgarside-dev**
- 604076b | Lint GHA sync workflows too
- 6b6b90a | Add actionlint PCH
- 2d96503 | Add logging to actionlint GHA
- d076123 | Add output -.-
- 2626fe2 | Fix output ;_;
- 98ef6c7 | Working?!
- 84b548e | Fix bad workflow

### CODE REVIEW

**Review by worgarside — APPROVED** [review]

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/550

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/552

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/553

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/553

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/554

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/555

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant/pull/404
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160
- https://github.com/worgarside/wg-utilities/pull/557

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Comment by worgarside-dev** [comment]
# Repo Sync PRs

- https://github.com/worgarside/addon-item-warehouse/pull/41
- https://github.com/worgarside/addon-rss-log-feed/pull/62
- https://github.com/worgarside/addon-yas-209-bridge/pull/59
- https://github.com/worgarside/home-assistant-config-validator/pull/56
- https://github.com/worgarside/led-matrix-now-playing/pull/53
- https://github.com/worgarside/plant-monitor/pull/77
- https://github.com/worgarside/python-template/pull/16
- https://github.com/worgarside/smart-mini-crt-interface/pull/117
- https://github.com/worgarside/very-slow-movie-player/pull/111
- https://github.com/worgarside/wg-scripts/pull/160

**Pull request merged**
